#!/usr/bin/env node
// Coverage generator (ADR 0041) — derives COVERAGE.md, the walk
// goal → serving record → criteria evidence state → plan items.
// Derived artefact, never hand-edited; deterministic (no timestamps).
//
// Usage: node scripts/coverage.mjs          # (re)write COVERAGE.md
//        node scripts/coverage.mjs --check  # exit 1 if COVERAGE.md is stale
//
// The verify gate's coverage-sync check calls --check; keep this
// generator's read logic aligned with scripts/verify.mjs (criteria
// regex mirrors check G).

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(join(root, rel), 'utf8').replace(/\r\n/g, '\n');

// ── Parse AC-bearing records (catalogue ADRs + specs, templates excluded) ──
function frontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { fields: null, body: text };
  const fields = {};
  for (const line of m[1].split('\n')) {
    const f = line.match(/^([\w-]+):\s*(.*)$/);
    if (f) fields[f[1]] = f[2].trim();
  }
  return { fields, body: m[2] };
}
const parseList = (v) => (v?.match(/"[^"]+"|[\w/-]+/g) ?? [])
  .map((s) => s.replace(/"/g, '')).filter((s) => s !== '[]' && s !== '');

// ── Parse goals/ (one file per goal; template excluded) ──
const goalsDir = join(root, 'goals');
if (!existsSync(goalsDir)) {
  console.error('goals/ not found — the goals layer is not enabled; nothing to generate.');
  process.exit(2);
}
const goals = []; // { id, title, state }
for (const f of readdirSync(goalsDir).filter((n) => n.endsWith('.md') && n !== 'G-template.md').sort()) {
  const { fields } = frontmatter(read(`goals/${f}`));
  if (!fields) continue;
  goals.push({
    id: fields.id ?? f.replace(/\.md$/, ''),
    title: fields.title ?? '',
    state: fields.state ?? 'unknown',
  });
}
function criteriaOf(body) {
  const block = body.split(/^## Acceptance criteria\s*$/m)[1]?.split(/^## /m)[0] ?? '';
  return [...block.matchAll(/^(\d+)\.\s/gm)].length;
}

const records = []; // { path, slug, title, status, serves[], acTotal, acEvidenced }
const sources = [];
if (existsSync(join(root, 'adr'))) {
  for (const f of readdirSync(join(root, 'adr')).filter((n) => n.endsWith('.md') && !n.includes('template'))) {
    sources.push(`adr/${f}`);
  }
}
if (existsSync(join(root, 'spec'))) {
  for (const f of readdirSync(join(root, 'spec')).filter((n) => n.endsWith('.md') && !n.startsWith('0000-'))) {
    sources.push(`spec/${f}`);
  }
}
for (const rel of sources.sort()) {
  const { fields, body } = frontmatter(read(rel));
  if (!fields) continue;
  const serves = parseList(fields.serves);
  if (!serves.length) continue;
  const slug = rel.replace(/^(adr|spec)\//, '').replace(/\.md$/, '');
  const acTotal = criteriaOf(body);
  const evDir = join(root, 'evidence', slug);
  const acEvidenced = existsSync(evDir)
    ? new Set(readdirSync(evDir).map((n) => n.match(/^AC(\d+)-\d{3}\.md$/)?.[1]).filter(Boolean)).size
    : 0;
  records.push({ path: rel, slug, title: fields.title ?? slug, status: fields.status ?? '?', serves, acTotal, acEvidenced });
}

// ── Plan items naming a serving record ──
const planRefs = (slug) => {
  const hits = [];
  for (const dir of ['plan/todo', 'plan/done', 'plan/dropped']) {
    if (!existsSync(join(root, dir))) continue;
    for (const f of readdirSync(join(root, dir)).filter((n) => n.endsWith('.md'))) {
      if (read(`${dir}/${f}`).includes(slug)) hits.push(`${dir.replace('plan/', '')}/${f.replace(/\.md$/, '')}`);
    }
  }
  return hits.sort();
};

// ── Render ──
const lines = [
  '# Coverage',
  '',
  '<!-- Generated by scripts/coverage.mjs — do not edit. Regenerate:',
  'node scripts/coverage.mjs -->',
  '',
  'The walk goal → serving record → criteria evidence → plan items.',
  '',
];
for (const g of goals) {
  lines.push(`## ${g.id} — ${g.title} (${g.state})`, '');
  const serving = records.filter((r) => r.serves.includes(g.id));
  if (!serving.length) {
    lines.push(
      g.state === 'Active'
        ? 'No serving records — an aspiration until something serves it.'
        : 'No serving records.',
      '',
    );
    continue;
  }
  lines.push('| Serving record | Status | Evidence | Plan items |', '|---|---|---|---|');
  for (const r of serving) {
    const ev = r.acTotal ? `${r.acEvidenced}/${r.acTotal} criteria` : 'no criteria';
    const plans = planRefs(r.slug);
    lines.push(`| ${r.path} | ${r.status} | ${ev} | ${plans.length ? plans.join(', ') : '—'} |`);
  }
  lines.push('');
}
const out = lines.join('\n');

if (process.argv.includes('--check')) {
  const current = existsSync(join(root, 'COVERAGE.md')) ? read('COVERAGE.md') : null;
  if (current === null) {
    console.error('COVERAGE.md missing while goals/ exists — regenerate.');
    process.exit(1);
  }
  if (current.trimEnd() !== out.trimEnd()) {
    console.error('COVERAGE.md is stale — regenerate with: node scripts/coverage.mjs');
    process.exit(1);
  }
  console.log('coverage: in sync');
} else {
  writeFileSync(join(root, 'COVERAGE.md'), out + '\n');
  console.log(`COVERAGE.md written (${goals.length} goals, ${records.length} serving records)`);
}
